var GAME_LEVELS = [

  ["                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                              xxx x  x xxx  xx  xx   x  xxx  x                               ",
   "                               x  x  x  x  x  x x x  x  x x  x                               ",
   "                               x  x  x  x  x  x xx   x  xxx  x                               ",
   "                               x   xx   x   xx  x x  x  x x  xxx                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                k                                            ",
   "                                @     o    o    d    o    o                                  ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",],

  ["                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                      o   o   o   o   o   o       o                          ",
   "     o   o           yyyyyyyyyyyyyyyyyyyyyyyy   xxxww    xxx         xxx     ",
   "                    y                               ^    x             x     ",
   "   o       o       y                        o            x    xx       x     ",
   "    o     o       y                       !!xxx          x#            x     ",
   "     ooooo       y                        v              x           o x     ",
   "   yyyyyyyyyyyyyy                                 o      x          xx x     ",
   "                                                xxxww    x  o          x     ",
   "                                                    ^    x xx        # x     ",
   "                                                         x        o    x     ",
   "                                           xxx!!         x       xx    x     ",
   "                                   xxxx                  x   o         x     ",
   "                              +  o      o                x   xx        x     ",
   "                     xxxx       xx      xx               x      k      x     ",
   "       @             x       wwwwwwwwwwwwww              xoo+ooodooo+oox     ",
   "     xxxxx   xx      xooo    xxxxxxxxxxxxxx   o          xxyyyyyyyyyyyxx     ",
   "         x           xxxx                    yyy     o   xwwwwwwwwwwwwwx     ",
   "      oo x                                           o   xxxxxxxxxxxxxxx     ",
   " xx  xxxxx +   * xxxxxxxxxxxxxxxxxxx*xxxxx*xxxxxxxx  x                       ",
   "wwwwwwwwwwwwwx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "wwwwwwwwwwwwwx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "wwwwwwwwwwwwwx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                   xxxxxxxxxxx                                                    ",
   "                                                 xx           xx                                                  ",
   "                                                x               x                                                 ",
   "                                               x                 x                                                ",
   "                                               x  ooo       ooo  x                                                ",
   "                                               x oxxxo     oxxxo x                                                ",
   "                                               x ox!xo  @  ox!xo x                                                ",
   "                                               x oxvxo  x  oxvxo x                                                ",
   "                                                x ooo   x   ooo x                                                 ",
   "                                                x       x       x                                                 ",
   "                                                 x     xxx     x                                                  ",
   "                                                 x             x                                                  ",
   "                                                 x ooooooooooo x                                                  ",
   "                                                 x ooooooooooo x                                                  ",
   "                                                  xxxxx   xxxxx                                                   ",
   "                                         xxx           x x           xxx                                          ",
   "                                        xxxxx  xx      x x      xx  xxxxx                                         ",
   "                                        xxx  x   xxxxxx   xxxxxx   x  xxx                                         ",
   "                                       x x   x                     x   x x                                        ",
   "                                       x x    xx     x  x  x     xx    x x                                        ",
   "                                       x x      xxxxx   x   xxxxx      x x                                        ",
   "                                       x x             yxy             x x                                        ",
   "                                       x x   x         |x|         x   x x                                        ",
   "                                       x x   xo         x         ox   x x                                        ",
   "                                       x xy   xx=    x  x  x    =xx   yx x                                        ",
   "                                       x x      xxxxx   x   xxxxx      x x                                        ",
   "                                       x x              x              x x                                        ",
   "                                       x x   x          x          x   x x                                        ",
   "                                       x x   xo         x         ox   x x                                        ",
   "                                       x x    xx=    x  x  x    =xx    x  x                                       ",
   "                                      x x       xxxxx   x   xxxxx       x x                                       ",
   "                                      x x  y            x            y  x x                                       ",
   "                                      x x    x          x          x    x x                                       ",
   "                                      x x    xo         x         ox    x x                                       ",
   "                                      x x     xx=    x  x  x    =xx     x x                                       ",
   "                                      x x       xxxxx   x   xxxxx       x x                                       ",
   "                                      x x               x               x x                                       ",
   "                                      x x              |x|              x x                                       ",
   "                                      x x              yxy              x x                                       ",
   "                                     xxxxxo             x             oxxxxx                                      ",
   "                                    xxxxxxx  ++         x         ++  xxxxxxx                                     ",
   "                                    x x x x                           x  xxxxx                                    ",
   "                                    x x x x  wwxxxxx         xxxxxww  x  x x x                                    ",
   "                                    x x x x  xx     xxx   xxx     xx  x  x x x                                    ",
   "                                    x x x   x                       x    x x x                                    ",
   "                                    x x x   x                       x    x x x                                    ",
   "                                      x     x   xxx           xxx   x      x                                      ",
   "                                            x  x   x    x    x   x  x                                             ",
   "                                            x  x    x   x   x    x  x                                             ",
   "                                            x   x   x       x   x   x                                             ",
   "                                             x   xxx         xxx   x                                              ",
   "                                              x       + k +       x                                               ",
   "                                              x     +   d   +     x                                               ",
   "                                               xxxwwwwwwxwwwwwwxxx                                                ",
   "                                            xxxx xwwwwwwwwwwwwwx xxxx                                             ",
   "                                             xxxx xxxxxxxxxxxxx xxxx                                              ",
   "                                              x x               x x                                               ",
   "                                              x x               x x                                               ",
   "                                              x x               x x                                               ",
   "                                              x x               x x                                               ",
   "                                              x x               x x                                               ",
   "                                              x x               x x                                               ",
   "                                              x x               x x                                               ",],
   ["                  ^               ^         ^              ^       ^     ^       ^         ^                                       ",
    "      ^                 ^                                            ^      ^        ^                ^        ^                   ",
    "                           ^                      ^                       ^       ^      ^    ^                            ^       ",
    "         ^                          ^                    ^      ^      ^       ^      ^   ^             ^            ^             ",
    "                   ^         ^                                                 ^    ^                          ^                   ",
    "  ^                                              ^                   ^    ^        ^    ^   ^  ^       ^                ^          ",
    "              ^               ^                                                ^                ^                                  ",
    "                                         ^                                    ^  ^     ^   ^                  ^         ^          ",
    "      ^                 ^                                               ^   ^       ^         ^   ^    ^                           ",
    "                           ^                      ^                   ^   ^     ^                                                  ",
    "         ^                          ^                    ^                ^             ^  ^         ^                             ",
    "                   ^         ^                                                     ^ ^                      ^               ^      ",
    "  ^                                              ^                   ^     ^       ^                                               ",
    "                             ^                                                                                    ^                ",
    "                                         ^                                                                                         ",
    "                                                                             xxxx                                                  ",
    "                                                                          xxxxxxxxxxx                                              ",
    "                                                                       xxx xxxxxx xx xxx                                           ",
    "                                                                     xx  x x xx     x   xx                                         ",
    "                                                                    x   x  xooox     x    x                                        ",
    "                                                                   x   x  xoooox      x    x                                       ",
    "                                                                  x    x  xooooox     x     x                                      ",
    "                                                                 x    x   xooooox      x     x                                     ",
    "          x     x                                                x    x  xoooooox      x     x                                     ",
    "          x     xx                                              x    x   xooooooox      x     x                                    ",
    "          x o   x x   o                                         x xxxx  xx xxoooox xxxx xxxxx x                                    ",
    "          x y   x  x                                            xx   xxx   x xx xxx    xxx   xx                                    ",
    "          x     x   x                                           x    x    ox x   x      x     x                                    ",
    "          x     x    x                                                    yx x                                       x             ",
    "          x     x                                                          x x                                      #x             ",
    "          x   y x       x                                                  x x o     o      o     o     o            x             ",
    "          x     x  o   x                                                o  x x x     x      x     x     x            x             ",
    "          x     x     x                                                 y  x x#                                      x             ",
    "          x     x    x                                                     x x   o      o      o      o              x             ",
    "          x y   x   x                                                      x x   x      x      x      x              x             ",
    "          x     x                            x                            ox x                                      #x             ",
    "          x     xx                          xx                            yx x o     o      o      o     o           x             ",
    "          x     x x                        xxxx                            x x x     x      x      x     x           x             ",
    "          x   y x  x                      xxxxxx                    xx     x x                                       x             ",
    "          x     x   x                    xxxxxxxx            yyy   x  x    x x          x       x                    x             ",
    "          x     x                       xxxxxx                     x  x    x x#                                      x             ",
    "          x   o x o               @          x        yyy           x  x  x x               k                        x             ",
    "          xxxxxxxxxxxxxxxxxxxxxxxxx   x o o ox d   x                x   xx  x             xxxxx                      x             ",
    "          xxxxxxxxxxxxxxxx            xxxxxxxxxxxxxx                 xx    x                                         x             ",
    "          xxxxxxxxxxxxxxxx         +   xxxxxxxxxxxx    +         +     xxxx                                          x             ",
    "          xxxxxxxxxxxxxxxx     +        xxxxxxxxxx          +                                                        x             ",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",],
    ["                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",
     "               o   o   ooo   o     o    o       o ooooo o     o   o o o                      ",
     "               o   o  o   o  o     o    o       o   o   oo    o   o o o                      ",
     "                o o  o     o o     o    o       o   o   o o   o   o o o                      ",
     "                 o   o     o o     o    o   o   o   o   o  o  o   o o o                      ",
     "                 o   o     o o     o    o  o o  o   o   o   o o   o o o                      ",
     "                 o    o   o   o   o     o o   o o   o   o    oo                              ",
     "                 o     ooo     ooo       o     o  ooooo o     o   o o o                      ",
     "                                                                                             ",
     "   @                                                                                         ",
     "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
     "                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",
     "                                                                                             ",],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
